[package]
name = "wordle_finder"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["advanced"] }
iced_widget = { version = "0.14.2" }
iced_core = { version = "0.14.0" }
